### ISSUE TITLE
Add option to remove Second-factor backup codes 

### ISSUE THREAD

**Issue by T0mWz** [owncloud/twofactor_backup_codes#17]
When two factor backup codes are generated, there is no option to remove the backup codes afterwards.
Also when the TOTP option is disabled, the 2FA backup code is still required. 
Could you add something of a button to remove them? 

Thanks! 😃

**Comment by karakayasemi** [comment]
Remove option looks reasonable. For your other comment, actually, backup_codes should not be enabled if there is no enabled second factor for the user. It is designed in this way. It indicates a bug in this function: https://github.com/owncloud/twofactor_backup_codes/blob/master/lib/Provider/BackupProvider.php#L111 . I will look at it when I find time.
Thank you for your feedback.

**Comment by karakayasemi** [comment]
I forgot to add, you are welcome to contribute if you want to help us more. 😃

**Comment by mmattel** [comment]
Ping, any updates on that (last change is 2 months ago...)

**Comment by T0mWz** [comment]
Are there any plans for further development of this app? 😃

**Comment by karakayasemi** [comment]
Hi, we need to solve first CI problems to resolve this issue and continue development. Most of the owncloud repositories migrated from Travis CI to Drone and currently, Travis CI configuration is failing for this repo. I will look at it when I find more time. 

Thank you for patience. Also, as I said before feel free to help us by contributing. We are almost in Hacktoberfest. 😃

**Comment by karakayasemi** [comment]
Hi @T0mWz I implemented remove backup codes feature in #19 . If you would like to help, you can test the functionality.

>
> Also when the TOTP option is disabled, the 2FA backup code is still required.

I checked the code again for this situation. Unfortunately this problem is not easy to fix due to inter class dependencies. Currently, if no any other twofactor provider option exist for the user, 2FA backup code is not shown. However, if any other 2FA exist and user is allowed to use it, the backup codes shown. I believe with remove backup codes feature, this will be less annoying.
